### ISSUE TITLE
Colorbar not right at highest value  bin (sometimes)

### ISSUE THREAD

**Issue by ta440** [tommbendall/tomplot#6]
Sometimes the highest value bin on the colorbar, above the reds, is set to blue again. This is quite confusing, as the very lowest and highest bins have the same color.
![nair_lauritzen_non_div_slotted_cylinder_t_day0 0](https://github.com/tommbendall/tomplot/assets/75810156/fbea108c-bf05-4368-b1c0-879bdde334ca)

**Comment by tommbendall** [comment]
We solved this by removing the `remove_contour=0.0` line from the call to `tomplot_contours`. This should throw an error if trying to remove the top or bottom contour! I'll leave this issue open until that is fixed

**Comment by tommbendall** [comment]
Closing as I think this was fixed by #17
